name: deploy

on:
  push:
    branches: [ main ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - name: Set up JDK 1.8
      uses: actions/setup-java@v1
      with:
        java-version: 1.8
    - name: Build with Maven
      run: mvn -B package --file pom.xml
    - name: Generate ssh key
      run: echo "$SSH_PRIVATE_KEY" > key && chmod 600 key
      env:
        SSH_PRIVATE_KEY: ${{ secrets.SSH_PRIVATE_KEY }}
    - name: Service Stop
      run: ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST -p $SSH_PORT  "sudo systemctl stop macaroni-bot"
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    - name: Deploy
      run: rsync -rlptgoD --delete --include='*.jar' --exclude='*' -e "ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null -p ${SSH_PORT}" target/ $SSH_USER@$SSH_HOST:$DEPLOY_PATH
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        DEPLOY_PATH: ${{ secrets.DEPLOY_PATH }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    - name: Service Start
      run: ssh -i ./key -o StrictHostKeyChecking=no -o UserKnownHostsFile=/dev/null $SSH_USER@$SSH_HOST -p $SSH_PORT  "sudo systemctl start macaroni-bot"
      env:
        SSH_USER: ${{ secrets.SSH_USER }}
        SSH_PORT: ${{ secrets.SSH_PORT }}
        SSH_HOST: ${{ secrets.SSH_HOST }}
    # 上記までの処理が成功した場合、以下のSlack通知処理が実行される
    - name: Slack Notification Success
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_COLOR: '#5cb85c'
        SLACK_TITLE: 'Success to Deploy to GitHub Pages :rocket:'
        SLACK_MESSAGE: ':closed_book: ${{ github.repository }}' 

    # 上記までの処理のいずれかが失敗した場合、以下のSlack通知処理が実行される
    - name: Slack Notification Failure
      if: failure()
      uses: rtCamp/action-slack-notify@v2.0.0
      env:
        SLACK_WEBHOOK: ${{ secrets.SLACK_INCOMING_WEBHOOK_URL }}
        SLACK_COLOR: '#dc143c'
        SLACK_TITLE: 'Failure to Deploy to GitHub Pages :boom:'
        SLACK_MESSAGE: ':closed_book: ${{ github.repository }}'
